apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: prometheus-config
data:
  rules.yml: |
    groups:
    - name: test-node-mem
      rules:
      - alert: NodeMemoryUsage
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 80
        for: 2m
        labels:
          team: node
        annotations:
          summary: "{{$labels.instance}}: High Memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 80% (current value is: {{ $value }}"
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    # remote_write:    # 远程写入到远程 VM 存储
    # - url: http://victoria-metrics:8428/api/v1/write

    # alerting:
    #   alertmanagers:
    #     - static_configs:
    #         - targets: ["alertmanager:9093"]
    
    # rule_files:
    # - /etc/prometheus/rules.yml

    scrape_configs:
      # - job_name: prometheus
      #   static_configs:
      #   - targets:
      #     - 139.198.167.220:30999

      # - job_name: example-random
      #   static_configs:
      #   - targets:
      #     - test-client-svc:80

      # - job_name: redis
      #   static_configs:
      #   - targets:
      #     - redis:9121

    - job_name: 'nodes'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
        action: replace
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: 'endpoints'
      kubernetes_sd_configs:
      - role: endpoints
      metric_relabel_configs:
      - source_labels: [__name__, exported_pod]
        regex: kube_pod_info;(.+)
        target_label: pod
      - source_labels: [__name__, exported_namespace]
        regex: kube_pod_info;(.+)
        target_label: namespace
      - source_labels: [__name__, exported_node]
        regex: kube_node_info;(.+)
        target_label: node
      - source_labels: [__name__, exported_service]
        regex: kube_service_info;(.+)
        target_label: service
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+):(?:\d+);(\d+)
        replacement: $1:$2
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
