---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitor
spec:
  type: NodePort
  ports:
    - port: 8428
      targetPort: 8428
      nodePort: 32121
  selector:
    app: victoria-metrics
